/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ScannerExitRouteImport } from './routes/scanner.exit'
import { Route as ScannerEntryRouteImport } from './routes/scanner.entry'
import { Route as BookingIdRouteImport } from './routes/booking.$id'
import { Route as AdminSlotsRouteImport } from './routes/admin.slots'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'

const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerExitRoute = ScannerExitRouteImport.update({
  id: '/scanner/exit',
  path: '/scanner/exit',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerEntryRoute = ScannerEntryRouteImport.update({
  id: '/scanner/entry',
  path: '/scanner/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlotsRoute = AdminSlotsRouteImport.update({
  id: '/admin/slots',
  path: '/admin/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/booking/$id': typeof BookingIdRoute
  '/scanner/entry': typeof ScannerEntryRoute
  '/scanner/exit': typeof ScannerExitRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/booking/$id': typeof BookingIdRoute
  '/scanner/entry': typeof ScannerEntryRoute
  '/scanner/exit': typeof ScannerExitRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/booking/$id': typeof BookingIdRoute
  '/scanner/entry': typeof ScannerEntryRoute
  '/scanner/exit': typeof ScannerExitRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/admin/reports'
    | '/admin/slots'
    | '/booking/$id'
    | '/scanner/entry'
    | '/scanner/exit'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/admin/reports'
    | '/admin/slots'
    | '/booking/$id'
    | '/scanner/entry'
    | '/scanner/exit'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/admin/reports'
    | '/admin/slots'
    | '/booking/$id'
    | '/scanner/entry'
    | '/scanner/exit'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSlotsRoute: typeof AdminSlotsRoute
  BookingIdRoute: typeof BookingIdRoute
  ScannerEntryRoute: typeof ScannerEntryRoute
  ScannerExitRoute: typeof ScannerExitRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner/exit': {
      id: '/scanner/exit'
      path: '/scanner/exit'
      fullPath: '/scanner/exit'
      preLoaderRoute: typeof ScannerExitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner/entry': {
      id: '/scanner/entry'
      path: '/scanner/entry'
      fullPath: '/scanner/entry'
      preLoaderRoute: typeof ScannerEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/slots': {
      id: '/admin/slots'
      path: '/admin/slots'
      fullPath: '/admin/slots'
      preLoaderRoute: typeof AdminSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSlotsRoute: AdminSlotsRoute,
  BookingIdRoute: BookingIdRoute,
  ScannerEntryRoute: ScannerEntryRoute,
  ScannerExitRoute: ScannerExitRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
